### ISSUE TITLE
Need larger modifier set

### ISSUE THREAD

**Issue by moos** [jimkang/fuck-shit-up#2]
Current set gets repetitive pretty quickly. Do you have any plans for expanding it?  (e.g., https://en.wiktionary.org/wiki/Category:English_vulgarities, I'm sure there are other lists).

**Comment by jimkang** [comment]
I was thinking of adding more modifiers, but my primary use case is to intensify sentences, rather than to make them disparaging. (I use this module for [these](https://twitter.com/fuckingbard) [bots](https://twitter.com/goddamn_factbot).) So, a lot of those won't work for that, but it's a big list, and I should look through them.

However, would custom modifier support and config file work better for what you want to do?

**Comment by sjlxndr** [comment]
maybe a "-disparage" command line flag would be in order ;-)

**Comment by moos** [comment]
I'd like to use this from the CLI -- so custom modifiers wouldn't work.  Perhaps something along what @sjalex suggested would work to tailor the degree/tone of intensity for different applications.

Your "Goddam Facts" bot is interesting.  In fact I was working on a bot to pull from clues j-archive.com and running them through fsu:

It controls most fucking language functions.
What is the motherfucking left goddamn brain.

**Comment by moos** [comment]
I've pulled some more modifiers the goddamn from various sources. They fucking seem to mothafucking mesh well fucking together. Choices are the goddamn definitely subjective. I've ROFLMGDMFAO left out nympho taboo or those of shitty questionable value.

More samples:

Up yours current bloody set gets shitty repetitive ROFLMGDMFAO pretty jackassed quickly.

Shitty current set gets mothafucking repetitive pretty fucktarded quickly.

Bleeping current fucking set gets Jesus H. Christ repetitive goddamn pretty the apeshit quickly.

The shitty rain in dumbass Spain stupid ass stays the goddamn mainly in the mothafucking plain.

**Comment by jimkang** [comment]
Yes – they definitely flow well. Sorry I let this issue slide the bollocks out of my goddamn brain, and thanks for the PR!

Please me know when your Jeopardy bot is up and running!

**Comment by moos** [comment]
Not sure if there is room for two jeopardy bots -- in the meantime checkout: https://twitter.com/dronegumpy
